CREATE DATABASE IF NOT EXISTS sartenes_db;

USE sartenes_db;

CREATE TABLE IF NOT EXISTS PlatosDelDia (
    id_plato INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    valor DECIMAL(5, 2) NOT NULL,
    imagen_url VARCHAR(255),
    activo TINYINT(1) DEFAULT 0,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
